# Investigating PyTorch tensor functions

### Exploring basic PyTorch methods

PyTorch: As per [pytorch.org](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html) "PyTorch is defined as a Python-based scientific computing package that targets to replace NumPy, and use the power of GPUs. It is also a platform to perform deep learning algorithms".

Tensors are usually defined as multi dimensional arrays, but that's not what they fundamentally are. 
"In the general case, an array of numbers arranged on a regular grid with a variable number of axes is known as a tensor."
[Goodfellow et al.](https://https://books.google.co.in/books?id=omivDQAAQBAJ&pg=PA31&lpg=PA31&dq=%22In+the+general+case,+an+array+of+numbers+arranged+on+a+regular+grid+with+a+variable+number+of+axes+is+known+as+a+tensor.%22&source=bl&ots=MMV_gutzTR&sig=ACfU3U3YklYd09NLcSMItxtBp26W2z9sbQ&hl=en&sa=X&ved=2ahUKEwjctbOHh9rpAhX9yzgGHW-tBawQ6AEwAHoECAkQAQ#v=onepage&q=%22In%20the%20general%20case%2C%20an%20array%20of%20numbers%20arranged%20on%20a%20regular%20grid%20with%20a%20variable%20number%20of%20axes%20is%20known%20as%20a%20tensor.%22&f=false)

Tensors have a geometric meaning: [ref](https://https://www.youtube.com/watch?v=TvxmkZmBa-k&list=PLJHszsWbB6hrkmmq57lX8BV-o-YIOFsiG&index=2)
1.   Tensors as an object are invariant under change of coordinates, but tensors have components that change in a special predictable way under a change of coordinates.
2.   Tensor is a collection of vectors and covectors combined together using tensor product.


A scalar (e.g.) is zero-order tensor or rank zero tensor. A vector(e.g.) is a one-dimensional or first order tensor, and a matrix(e.g.) is a two-dimensional or second order tensor.

- torch.where()
- torch.mean()
- torch.split()
- torch.t()
- torch.bitwise_and()

Bonus:  I will create tensors in different ways while exploring these 5 functions :)

In [0]:
# Import torch and other required modules
import torch
import numpy

## Function 1 - TORCH.WHERE

**torch.where(condition, x, y) → Tensor**

Return a tensor of elements selected from either x or y, depending on condition.















In [5]:
# Example 1 (tensor using matrix)
x=torch.tensor([[1, 2], [3, 4.]])
y=torch.tensor([[5., 6], [7, 8.]])
torch.where(x > 2.2, x, y)

tensor([[5., 6.],
        [3., 4.]])

Replaces elements in x with elements in y if condition (x > 2.2) is not satisfied




In [7]:
# Example 2 (tensor using torch.randn())
x = torch.randn(3, 2)
y = torch.randn(3, 2)
print(x)
print(y)
torch.where(x > 1, x, y)

tensor([[-0.7452, -0.1453],
        [ 0.3297,  0.7475],
        [-0.3480,  0.6352]])
tensor([[ 0.3257,  2.4023],
        [ 0.9102, -1.1516],
        [-0.9089, -1.1275]])


tensor([[ 0.3257,  2.4023],
        [ 0.9102, -1.1516],
        [-0.9089, -1.1275]])

Replaces elements in x with elements in y if condition (x > 1) is not satisfied

In [44]:
# Example 3 - breaks () - (tensor using zeros() and ones())
x = torch.zeros(3, 4)
y = torch.ones(3, 2) # fails 
#y=torch.tensor([[1.], [2.], [3.]]) # works
#y = torch.ones(3, 1) # works 
#y=torch.tensor([[1.], [2.], [3.], [4.]]) # fails : The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0
#y=torch.tensor([ [1, 2.],[5., 6], [7, 8.]]) #fails : The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 1
print(x)
print(y)
torch.where(x==0, x, y)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


RuntimeError: ignored

Does not work when there is size mismatch of tensors

In [45]:
# Example 4 - breaks () - (tensor using zeros() and ones())
x = torch.zeros(3, 2)
y = torch.ones(3, 2)
print(x)
print(y)
torch.where(x!="a", x, y)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


TypeError: ignored

Does not work when condition returns a bool, it should be BoolTensor.

Expected parametes
*   condition (BoolTensor) – When True (nonzero), yield x, otherwise yield y
*   x (Tensor) – values selected at indices where condition is True
*   y (Tensor) – values selected at indices where condition is False


## Function 2 - TORCH.MEAN

**torch.mean(input) → Tensor**

Returns the mean value of all elements in the input tensor.

In [79]:
# Example 1 - (tensor using as_tensor())
n = numpy.array([3., 4., 5.])
t = torch.as_tensor(n) # creating from existing Tensor : given that the two tensors are of the same dtype no copy will be performed
torch.mean(t)

tensor(4., dtype=torch.float64)

calculates mean of 1d tensor

In [75]:
# Example 2 - using dim for reduction

x = torch.randn(3, 2)
print(x)
# dim=0
print(torch.mean(x,dim=0)) # over rows, get a mean for each col
# dim=1
print(torch.mean(x,dim=1)) # over cols, get a mean for each row
# reduce over both dimensions
print(torch.mean(x,dim=[0,1]))
# keepdim keeps original dim of tensor in mean result
print(torch.mean(x,dim=1, keepdim=True))


tensor([[ 1.8453,  1.0074],
        [ 0.9376, -0.2669],
        [-0.6401,  1.2290]])
tensor([0.7143, 0.6565])
tensor([1.4263, 0.3353, 0.2945])
tensor(0.6854)
tensor([[1.4263],
        [0.3353],
        [0.2945]])


Function gives mean value of input tensor in the given dimension dim. If we give a list of dimensions, it reduces over all of them.

If keepdim is True, input tesnor size is maintained in output tensor.

In [114]:
# Example 3 - breaks 
n = numpy.array([3, 4, 5])
t = torch.as_tensor(n) # creating from existing Tensor : given that the two tensors are of the same dtype no copy will be performed
torch.mean(t)
#t.float().mean() # work around

RuntimeError: ignored

Can only calculate the mean of floating types



Expected parametes:

*   input (Tensor) – the input tensor.
*   dim (int or tuple of python:ints) – the dimension or dimensions to reduce.
*   keepdim (bool) – whether the output tensor has dim retained or not.
*   out (Tensor, optional) – the output tensor.









## Function 3 - TORCH.SPLIT

torch.split(tensor, split_size_or_sections, dim=0)

Splits the tensor into chunks. Each chunk is a view of the original tensor.

In [90]:
# Example 1 - (tensor using torch.linspace())
t = torch.linspace(start=1., end=9., steps=12) # Returns 1d tensor of steps size equally spaced points between start and end
print(t)
print(torch.split(t, split_size_or_sections=2))

tensor([1.0000, 1.7273, 2.4545, 3.1818, 3.9091, 4.6364, 5.3636, 6.0909, 6.8182,
        7.5455, 8.2727, 9.0000])
(tensor([1.0000, 1.7273]), tensor([2.4545, 3.1818]), tensor([3.9091, 4.6364]), tensor([5.3636, 6.0909]), tensor([6.8182, 7.5455]), tensor([8.2727, 9.0000]))


splits tensor t in chunks of size 2

In [96]:
# Example 2 - using dim
u = torch.randn(3, 4)
print(u)
print(torch.split(u, split_size_or_sections=2, dim=0)) # over rows
print(torch.split(u, split_size_or_sections=2, dim=1)) # over cols
print(torch.split(u, split_size_or_sections=(1,2), dim=0)) # over rows

tensor([[ 0.1789,  0.0437,  0.1664, -0.7739],
        [ 0.4889,  1.5820,  1.7294, -1.0538],
        [ 0.2536,  1.1255,  0.3223,  0.1015]])
(tensor([[ 0.1789,  0.0437,  0.1664, -0.7739],
        [ 0.4889,  1.5820,  1.7294, -1.0538]]), tensor([[0.2536, 1.1255, 0.3223, 0.1015]]))
(tensor([[0.1789, 0.0437],
        [0.4889, 1.5820],
        [0.2536, 1.1255]]), tensor([[ 0.1664, -0.7739],
        [ 1.7294, -1.0538],
        [ 0.3223,  0.1015]]))
(tensor([[ 0.1789,  0.0437,  0.1664, -0.7739]]), tensor([[ 0.4889,  1.5820,  1.7294, -1.0538],
        [ 0.2536,  1.1255,  0.3223,  0.1015]]))


splits tensor in chunks of size ( 2 here ) over rows and columns. Even if in first case there are 3 rows it chunks them in size of 2 and 1 rows respectively. In case 3 we define a tuple of chunk size it breaks according to that.

In [95]:
# Example 3 - breaks
u = torch.randn(3, 4)
print(u)
print(torch.split(u, split_size_or_sections=4., dim=0)) # over rows

tensor([[-0.5835,  0.0907, -0.5211,  1.4516],
        [ 1.0705, -0.7646, -0.5101, -0.2664],
        [-0.2857, -0.5704, -2.1008,  0.2457]])


TypeError: ignored

In [99]:
# Example 4 - breaks
u = torch.randn(5, 5)
print(u)
print(torch.split(u, split_size_or_sections=(1,2), dim=0)) # over rows

tensor([[ 0.0609,  1.0277, -0.3581,  2.4716,  1.7454],
        [-0.3646, -0.1950,  1.1079,  0.1040, -1.0458],
        [ 1.2728, -0.0054,  1.0381, -0.7885, -1.9321],
        [-0.5108,  0.5186, -1.4755, -1.3868,  0.2217],
        [ 0.3797,  1.3976, -1.3833,  1.1213,  1.9535]])


RuntimeError: ignored

split_with_sizes() must be tuple of ints, not float  

split_with_sizes expects split_sizes to sum exactly to 5

Expected parametes:

*   tensor (Tensor) – tensor to split.

*   split_size_or_sections (int) or (list(int)) – size of a single chunk or list of sizes for each chunk

*   dim (int) – dimension along which to split the tensor.



## Function 4 - TORCH.T

**torch.t(input) → Tensor**

Transposes a tesnor.

In [112]:
# Example 1 - (tensor using torch.as_strided)
t1 = torch.randn(3, 3)
print(t1)
t2 = torch.as_strided(t1, (2, 2), (1, 2)) # to get some "stepped" or "strided" values from an existing tensor
print(t2)
torch.t(t2)


tensor([[-0.3890, -0.9093, -0.5712],
        [-0.7746, -0.0201, -0.4771],
        [-0.0539, -3.0266, -0.0985]])
tensor([[-0.3890, -0.5712],
        [-0.9093, -0.7746]])


tensor([[-0.3890, -0.9093],
        [-0.5712, -0.7746]])

Explanation about example

In [119]:
# Example 2 - (tensor using numpy.array)
t1=torch.tensor(numpy.array([[1, 0., 1], [0., 1, 1]]), dtype=torch.bool)
print(t1)
torch.t(t1)

tensor([[ True, False,  True],
        [False,  True,  True]])


tensor([[ True, False],
        [False,  True],
        [ True,  True]])

Explanation about example

In [122]:
# Example 3 - breaks (as expected, works for 2d only)
t1 = torch.randn(3, 3, 3)
print(t1)
torch.t(t1)

tensor([[[ 0.0271, -0.1443,  0.0132],
         [ 2.2322,  0.7974,  0.6261],
         [-1.4108,  0.9880, -0.9253]],

        [[-0.3904,  0.4604,  0.5524],
         [-0.1336,  3.1019, -1.0437],
         [ 0.7046,  0.9866,  0.5504]],

        [[ 0.3070, -0.8057,  1.9325],
         [-0.2559,  0.4919, -2.0769],
         [ 0.2263,  0.7113, -0.4130]]])


RuntimeError: ignored

Expects input to be <= 2-D tensor and transposes dimensions 0 and 1

Function returns scalar and 1d tensors as is. For 2d tesnors it is equivalent to transpose(input, 0, 1).

Expected parameters:

*  input – the input tensor

## Function 5 - TORCH.BITWISE_AND

**torch.bitwise_and(input, other, out=None) → Tensor**

Computes the bitwise AND

In [139]:
# Example 1 - (tensor using torch.ararnge())
t1 = torch.arange(4)
t2 = torch.tensor([1,1,2,1])
print(t1)
print(t2)
torch.bitwise_and(t1, t2)

tensor([0, 1, 2, 3])
tensor([1, 1, 2, 1])


tensor([0, 1, 2, 1])

does bit wise AND for elements of t1 and t2 respectively

In [140]:
# Example 2 
t1=torch.tensor(numpy.array([[1, 0., 1], [0., 1, 1]]), dtype=torch.bool)
t2=torch.tensor(numpy.array([[0, 0., 1], [1., 1, 1]]), dtype=torch.bool)
print(t1)
print(t2)
torch.bitwise_and(t1, t2)

tensor([[ True, False,  True],
        [False,  True,  True]])
tensor([[False, False,  True],
        [ True,  True,  True]])


tensor([[False, False,  True],
        [False,  True,  True]])

Computes the logical AND for bool tensors

In [142]:
# Example 3 - breaks for float
t1 = torch.tensor([[1, 0], [2., 4.]])
t2 = torch.tensor([[1, 0], [3, 4.]])
print(t1)
print(t2)
torch.bitwise_and(t1, t2)

tensor([[1., 0.],
        [2., 4.]])
tensor([[1., 0.],
        [3., 4.]])


RuntimeError: ignored

"bitwise_and_cpu" not implemented for 'Float'


In [143]:
# Example 4 - breaks for diff dimensions
t1 = torch.tensor([[1, 0, 1], [2., 4.,3]])
t2 = torch.tensor([[1, 0], [3, 4.]])
print(t1)
print(t2)
torch.bitwise_and(t1, t2)

tensor([[1., 0., 1.],
        [2., 4., 3.]])
tensor([[1., 0.],
        [3., 4.]])


RuntimeError: ignored

Size should be same


The input tensor must be of integral or Boolean types. 

Expected parameters:

*  input – the first input tensor

*  other – the second input tensor

*  out (Tensor, optional) – the output tensor

## Conclusion

This article is a peek to week 1 of course entitled Deep Learning with PyTorch - Zero to GANs.

It's a 6 weeks [course](https://jovian.ml/forum/t/official-course-announcements/1189), livestreamed in freeCodeCamp.org's YouTube page.

Refer the full code here: https://jovian.ml/s. For more functions and details visit official PyTorch [docs](https://pytorch.org/docs/stable/tensors.html). 


## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* ...

In [0]:
#!pip install jovian --upgrade --quiet

In [145]:
import jovian

ModuleNotFoundError: ignored

In [0]:
jovian.commit()